export enum Constants {
  NS_IN_ONE_MS = 1e6,
  MS_IN_ONE_SECOND = 1000,
  MS_IN_ONE_MINUTE = MS_IN_ONE_SECOND * 60,
  MS_IN_ONE_HOUR = MS_IN_ONE_MINUTE * 60,
  MS_IN_ONE_DAY = MS_IN_ONE_HOUR * 24,
  MS_IN_ONE_WEEK = MS_IN_ONE_DAY * 7,
  MS_IN_ONE_MONTH = MS_IN_ONE_DAY * 30,
  MS_IN_ONE_YEAR = MS_IN_ONE_DAY * 365,

  BYTES_IN_ONE_KB = 1024,
  BYTES_IN_ONE_MB = BYTES_IN_ONE_KB * 1024,
  BYTES_IN_ONE_GB = BYTES_IN_ONE_MB * 1024,
  BYTES_IN_ONE_TB = BYTES_IN_ONE_GB * 1024,
  BYTES_IN_ONE_PB = BYTES_IN_ONE_TB * 1024,
}
